### ISSUE TITLE
css中使用background-image导致gulp进程崩溃，是否有解？

### ISSUE THREAD

**Issue by Dafrok** [cssdream/cssgrace#13]
错误信息：Corrupt JPG, exceeded buffer limits

**Comment by AMAID** [comment]
经过排查找到一种可能性 是美工给的图片头信息有问题
图片是由MAC的photoshopCC输出的 希望能有了解的人能解释一下这个问题

**Comment by yisibl** [comment]
只有某一张图片会有这个问题吗？换成 PNG 格式试试？

**Comment by AMAID** [comment]
@yisibl 美工给我的一批图片都有这个问题 有PNG也有JPG 大概10几张 尝试用image minify以及mspaint转存过都会崩

**Comment by yisibl** [comment]
换用 grunt 呢？

**Comment by AMAID** [comment]
@yisibl 我最近才学习的前端 没有用过grunt 如果需要debug的话我可以把出问题的文件提供给你
