### ISSUE TITLE
如果做了hack，会出现属性重复

### ISSUE THREAD

**Issue by sudosiyang** [cssdream/cssgrace#14]
这个是BUG，还是我应该注意，因为以前写的代码都做好了hack，不能在重复检查一次删除重复属性吧！
![1](https://cloud.githubusercontent.com/assets/5602140/6636737/e6e5e11c-c9ad-11e4-8da4-3c132cf240fe.png)

**Comment by AMAID** [comment]
cssgrace的目的是让你按标准写css 本身不标准的写法自然不予处理啦

**Comment by sudosiyang** [comment]
@AMAID 那这种重复不做一次过滤么。

**Comment by AMAID** [comment]
@sudosiyang 去重应该是预处理器需要关心的工作 不要在一个模块里完成太多的事 这样才符合符合高内聚低耦合的原则 提高效率 你目前的情况应该找一些压缩插件去完成这些事

`“而你，只用书写和关心标准的 CSS 语法。”`
readme中是这么写的 所以你让它去完成自己该做的工作就好啦

**Comment by sudosiyang** [comment]
ok,thanks

**Comment by yisibl** [comment]
可以使用  [clean-css](https://github.com/jakubpawlowicz/clean-css) 去除重复的属性问题，

**Comment by sudosiyang** [comment]
@yisibl 谢谢提醒
