### ISSUE TITLE
NPM Peer Dependency error

### ISSUE THREAD

**Issue by polarathene** [cssdream/cssgrace#34]
I have PostCSS 5 from earlier `npm install postcss`. When install cssgrace this cause conflict preventing install.

Windows 8.1 x64

![npm_error_cssgrace](https://cloud.githubusercontent.com/assets/5098581/9656680/29ba2412-528e-11e5-91fe-1c18de8329a1.PNG)

**Comment by Semigradsky** [comment]
:heavy_plus_sign:

**Comment by natezerk** [comment]
+1

**Comment by yodairish** [comment]
+1

**Comment by yisibl** [comment]
Thanks, done! https://github.com/cssdream/cssgrace/pull/39
