### ISSUE TITLE
Support for CSS Gradients

### ISSUE THREAD

**Issue by raeesiqbal** [cssdream/cssgrace#35]
```css
background: linear-gradient(to bottom, #ffffff 0%,#e2f4ff 100%);
```
can be converted to 
```css
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#e2f4ff',GradientType=0 ); /* IE6-9 */
```
I was wondering if CSS Grace can support this feature.

**Comment by yisibl** [comment]
I'm sorry, I don't have a plan for this. Welcome PR.

**Comment by yuezk** [comment]
@raeesiqbal , I'm about to write a plugin to handle this. I think CSS Grace will become a PostCSS plugin pack, and it can include the plugin if needed.

**Comment by raeesiqbal** [comment]
@yuezk Thank you.

**Comment by yisibl** [comment]
@yuezk Nice!

**Comment by yuezk** [comment]
@raeesiqbal Now, it' ready to use! [postcss-filter-gradient](https://github.com/yuezk/postcss-filter-gradient)

**Comment by raeesiqbal** [comment]
thank you :smile:
