### ISSUE TITLE
sth is deprecated 

### ISSUE THREAD

**Issue by vagusX** [cssdream/cssgrace#36]
postcss was renewed recently - https://github.com/postcss/postcss/releases/tag/5.0.9
and we see the following:

Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#before is deprecated. Use Node#raws.before

So, can u update it?

**Comment by yisibl** [comment]
Thanks, done! https://github.com/cssdream/cssgrace/pull/39
