### ISSUE TITLE
cssgrace@2.0.2 requires a peer of postcss@^4.0.0 but none was installed. (postcss 5)

### ISSUE THREAD

**Issue by Sly777** [cssdream/cssgrace#37]
cssgrace@2.0.2 requires a peer of postcss@^4.0.0 but none was installed.

npm version : 3.3.6
nodejs version : 4.2.1
postcss version : ^5.0.10

**Comment by polarathene** [comment]
https://github.com/cssdream/cssgrace/issues/34

This repo seems a bit inactive, a PR could be made but no idea when that would be accepted.

**Comment by yisibl** [comment]
Thanks, done! https://github.com/cssdream/cssgrace/pull/39
