### ISSUE TITLE
读取背景图片路径有问题

### ISSUE THREAD

**Issue by paddingme** [cssdream/cssgrace#38]
![snip20151105_2](https://cloud.githubusercontent.com/assets/5771087/10963523/04e645d8-83dc-11e5-92b8-3b1d7986df18.png)
![snip20151105_5](https://cloud.githubusercontent.com/assets/5771087/10963524/04ed128c-83dc-11e5-8711-b41e388aff47.png)

**Comment by yisibl** [comment]
Fix: https://github.com/cssdream/cssgrace/pull/39

**Comment by yisibl** [comment]
请稍后试试新版本，感谢反馈！
